---
- name: install k8s
  hosts: k8s_groups
  tasks:
  - name: install k8s
    shell: |
       curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
       && chmod +x minikube \
       && sudo mkdir -p /usr/local/bin/ \
       && sudo install minikube /usr/local/bin/
